manifest:
  remotes:
  - name: nxp
    url-base: https://github.com/NXP
  - name: nxp-zephyr
    url-base: https://github.com/nxp-zephyr
  - name: nxp-mcuxpresso
    url-base: https://github.com/nxp-mcuxpresso
  defaults:
    remote: nxp-mcuxpresso
  projects:
  - name: bifrost
    path: bifrost
    remote: nxp-zephyr
    revision: e68986be10e8087d678d8092a340f93700e34198
    west-commands: scripts/west_commands.yml
    groups:
    - bifrost
    userdata:
      track_branch: main
      branch_flow: false
  - name: core
    path: mcuxsdk/
    repo-path: mcuxsdk-core
    revision: cddfd29efcdbae9385727ed179da7297d5f684aa
    west-commands: scripts/west_commands.yml
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: main
      branch_flow: true
      display_name: Peripheral Driver
      description: Drivers for common use cases of hardware peripherals, simplifying
        access and integration.
  - name: CMSIS
    repo-path: mcu-sdk-cmsis
    path: mcuxsdk/arch/arm/CMSIS
    revision: dc8b75b360fce9c864a12f1ccc54172e0c733805
    groups:
    - core
    - ble_nxp
    userdata:
      track_branch: mcux_main
      branch_flow: false
      display_name: CMSIS
      description: Vendor-independent hardware abstraction layer for microcontrollers
        that are based on Arm Cortex processors, distributed by ARM.
  - name: mcux-soc-svd
    path: mcuxsdk/svd
    revision: 17f18904385082f2f06d0de0a0322e8c4f217fab
    groups:
    - optional
    userdata:
      track_branch: main
      branch_flow: false
      display_name: Device SVD
      description: System View Description (SVD) files for NXP MCU devices, providing
        detailed peripheral register definitions
  - name: mcu-sdk-examples
    revision: 7ccbb093b3922b88f376b467931fd8103413e073
    repo-path: mcuxsdk-examples
    path: mcuxsdk/examples
    groups:
    - examples
    - ble_nxp
    userdata:
      track_branch: main
      branch_flow: true
      display_name: Out-of-box Examples
      description: Out-of-box examples demonstrating peripheral driver usage and middleware
        integration.
  - name: mcu-sdk-components
    repo-path: mcux-component
    revision: f5d87422b7068c113493d7993cf847cbb4fd370f
    path: mcuxsdk/components
    groups:
    - components
    - ble_nxp
    userdata:
      track_branch: mcux_main
      branch_flow: true
      display_name: Components and Board Peripheral Drivers
      description: NXP MCU SDK components and board-specific peripheral driver libraries
  - name: mcu-sdk-doc
    repo-path: mcuxsdk-doc
    revision: 73a0ec26fae186e76167ee2d7a48f307a631055f
    path: mcuxsdk/docs
    west-commands: scripts/west_commands.yml
    groups:
    - doc
    userdata:
      track_branch: main
      branch_flow: false
      display_name: Documentation
      description: Documentation for NXP MCUXpresso SDK, providing comprehensive reference
        materials
  - name: mcuxsdk-tool-data
    revision: 275065efdccbf3b182602bcf5e63ada19c1ebe0d
    path: mcuxsdk/tool_data
    groups:
    - core
    userdata:
      track_branch: main
      branch_flow: false
      display_name: SDK Tool Data
      description: Additional tooling and configuration data for NXP MCU SDK development
        environment
